### PR TITLE
[Bugfix] Not found: Create for Collections.Mutable.MutableArraySegmen…

### PR DESCRIPTION
**Pull request by bsnbsn**
…t in WebSocketClient and WebSocketServer.

### CODE REVIEW

**Comment by bsnbsn** [comment]
After installing this package and opening the examples, I got the error message described above. This PR should fix this issue.

**Comment by joreg** [comment]
hey, thanks for this. but this should already work as is with latest stable 2021.4.10
have you maybe tried it with an earlier version?

**Comment by bsnbsn** [comment]
Hey, yes, I tried it with version 2021.4.9 - when I open vvvv in version 2021.4.10, I can find `Collections.Mutable.MutableArraySegement`. This makes this PR obsolete. I did not expect this to make a difference. Maybe worth to mention that in the readme? Anyway, I'll close this PR.

**Comment by joreg** [comment]
indeed. only since this is still a prerelease pack and still changing it is a bit hard to communicate which version it works with. typically latest stable!

**Pull request closed without merging**
